@startuml 
sprite $capability [61x61/8] {
_____________________________________________________________
_____________________________________________________________
_____________________________________________________________
_____________________________________________________________
_____________________________________________________________
_____________________________________________________________
____________00000000_________________________________________
___________0000000000_______00000000000000000000000__________
___________0000000000_______00000000000000000000000__________
____________000000000________________________________________
_____________________________________________________________
_____________________________________________________________
_____________________________________________________________
____________000__000_________________________________________
___________00_______0_______0000000000000000000000___________
___________00_______00______00000000000000000000000__________
____________00_____00________000000000000000000000___________
______________0000___________________________________________
_____________________________________________________________
_____________________________________________________________
_____________00__000_________________________________________
___________00_______0________000000000000000000000___________
___________00_______00______00000000000000000000000__________
___________00_______0________________________________________
_____________000000__________________________________________
_____________________________________________________________
_____________________________________________________________
_____________________________________________________________
_____________________________________________________________
_____________________________________________________________
_____________________________________________________________
}
@enduml