@startuml 
sprite $capability [61x61/8] {
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIJJRRRRRRJJIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIJRQHG88888HQRJIIIIIIIIRRRRRRRRRRRRRRRRRIIIIIIIIIIIII
IIIIIIIIJRIH000000008HRRRJRIHHHHHHHHHHHHHHHHHHHHHHHIIIIIIIIII
IIIIIIIIRR900000000009IRRRR900000000000000000000000IIIIIIIIII
IIIIIIIIRR900000000001IRRRR900000000000000000000000IIIIIIIIII
IIIIIIIIQRA1000000000ARRRRRAA111111111111111111111AIIIIIIIIII
IIIIIIIIIRRJA1111112JRRQIIIIJJJJJRRRRRRRRRRRRRJJJJJIIIIIIIIII
IIIIIIIIIIRRRRRJJJRRRRQIIIIIIIQRRRRRRRRRRRRRRRRRIIIIIIIIIIIII
IIIIIIIIIIRQQHG888HPQQJIIIIIJJRRRRRRRRRRRRRRRRRRRJIIIIIIIIIII
IIIIIIIIIJIH000110008HRJJJJQPPPPPPPPPPPPPPPPPPPPPPIIIIIIIIIII
IIIIIIIIIR9001JRRJA108IQRRR900000000000000000000008IIIIIIIIII
IIIIIIIIIR900HRRRRR900IIRRR900000000000000000000000IIIIIIIIII
IIIIIIIIIRA100HPPPG009IRRRRA10000000000000000000001IIIIIIIIII
IIIIIIIIIIII21000011AIQIIIQIRRRRRRRRRRRRRRRRRRRRRRRIIIIIIIIII
IIIIIIIIIIQRRJJAABJJRRIIIIIIIQRRRRRRRRRRRRRRRRRRQIIIIIIIIIIII
IIIIIIIIIIJRQPGGGGPPQRIIIIIIJJRRRRRRRRRRRRRRRRRRRJJIIIIIIIIII
IIIIIIIIIJIH80011000GHRJIJJIIHHHHPPPPPPPPPPPPPHHHHIIIIIIIIIII
IIIIIIIIIR9001IJJJA108IRRRR980000000000000000000008IIIIIIIIII
IIIIIIIIII900HRRRRR900IIRRR900000000000000000000000IIIIIIIIII
IIIIIIIIIR9008HQQQG801IRRRRA11111111111111111111111IIIIIIIIII
IIIIIIIIIIIA10000001AIQIIIQIIIIJJJJJJJJJJJJJJJJJIIIIIIIIIIIII
IIIIIIIIIIIIIJBBBBBIIQIIIIIIIIIQQQQQQQQQQQQQQQQQIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
}
@enduml